client:
  http_timeout: 15s
  api_version: v0
  base_url: "https://hacker-news.firebaseio.com"
  retry_wait: 1s
  max_attempts: 5

channels:
  new:
    process_after: 0s
    next: queue:30m
  "queue:30m":
    process_after: 30m
    next: queue:1h
  "queue:1h":
    process_after: 1h
    next: queue:3h
  "queue:3h":
    process_after: 3h
    next: queue:6h
  "queue:6h":
    process_after: 6h
    next:
