name: CI

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.x

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check formatting
      working-directory: producer
      run: |
        gofmt_diff=$(gofmt -d .)
        if [[ -n ${gofmt_diff} ]]; then
          exit 1
        fi

    - name: Vet
      working-directory: producer
      run: go vet

    - name: Test
      working-directory: producer
      run: go test ./...
